# Generated by Django 4.1.3 on 2022-12-05 10:35

from django.db import migrations, models
import django.db.models.deletion
import video_clips.utilities


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to=video_clips.utilities.get_timestamp_path, verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Выводить в списке?')),
                ('price', models.TextField(verbose_name='Цена')),
                ('url', models.URLField(verbose_name='Ссылка на видео')),
                ('created_dt', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата, время')),
                ('categ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='video_clips.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Все публикации',
                'ordering': ['-created_dt'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=video_clips.utilities.get_timestamp_path, verbose_name='Доп изображения')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_clips.video', verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Дополнительная иллюстрация',
                'verbose_name_plural': 'Дополнительные иллюстрации',
            },
        ),
    ]
