# Generated by Django 4.1.3 on 2022-12-05 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_clips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Все категории'},
        ),
    ]
